version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - |
        npm install
        npm install -g serverless
        serverless plugin install --name serverless-dynamodb-local
        serverless plugin install --name serverless-offline
  build:
    commands:
      - echo Entered the build phase...
      - echo Deploying the backend package...
      - |
        npm run deploy -- --verbose
  post_build:
    commands:
      - echo Entered the post_build phase..
      - |
        echo Checking if Build stage succeeded
        if [[ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]]; then
          echo "Build stage has failed. Exiting."
          exit 1
        fi
      - echo "Proceeding with Post-Build stage."
      - STAGE=$STAGE REGION=$AWS_DEFAULT_REGION npm run test:deployed
      - |
        ApiGwUrl=`serverless info --verbose --stage $STAGE --region $AWS_DEFAULT_REGION | grep '^ServiceEndpoint:' | grep -o 'https://.*'`
        aws ssm put-parameter --name "/$AWS_DEFAULT_REGION/$STAGE/" --description "API Gateway URL - $AWS_DEFAULT_REGION $STAGE" --value "$ApiGwUrl"  --type "String" --overwrite --tier "Standard" \
        --data-type "text" --tags "[{\"Key\": \"Region\",\"Value\": \"$AWS_DEFAULT_REGION\"},{\"Key\": \"Environment\",\"Value\": \"$STAGE\"},{\"Key\": \"Project\",\"Value\": \"$PROJECT\"}]"
        aws codebuild start-build --project-name "$WEB_CODEBUILD_NAME" --region $AWS_DEFAULT_REGION
