version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - sed -i "s/{{AWS_DEFAULT_REGION}}/$AWS_DEFAULT_REGION/g" serverless.yml 
      - |
        npm install
        npm install -g serverless
        serverless plugin install --name serverless-dynamodb-local
        serverless plugin install --name serverless-offline
  build:
    commands:
      - echo Entered the build phase...
      - echo Deploying the backend package...
      - |
        npm run deploy -- --verbose
  post_build:
    commands:
      - echo Entered the post_build phase..
      - |
        echo Checking if Build stage succeeded
        if [[ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]]; then
          echo "Build stage has failed. Exiting."
          exit 1
        fi
      - echo "Proceeding with Post-Build stage."
      - |
        ApiGwUrl=`serverless info --verbose --stage ${STAGE,,} --region $AWS_DEFAULT_REGION | grep '^ServiceEndpoint:' | grep -o 'https://.*'`
        aws configure set cli_follow_urlparam false
        aws ssm put-parameter --name "/${AWS_DEFAULT_REGION}/${STAGE,,}/ApiGwEndpoint" --description "API Gateway URL - $AWS_DEFAULT_REGION ${STAGE,,}" --value "$ApiGwUrl"  --type "String" --overwrite --tier "Standard" \
        --data-type "text"
        
